trigger:
  branches:
    include:
      - main

pool:
  name: "Comp367_SH_Agent"

variables:
  angularAppPath: './'
  dockerHubRepo: 'ronaldjrombao/comp367group'
  dockerfilePath: './Dockerfile'
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 8)]

stages:
- stage: AngularTestAndSonarQube
  displayName: Run Unit Tests and SonarQube
  jobs:
    - job: TestAndAnalyze
      displayName: Angular Test & Analysis
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '22.11'
          displayName: 'Use Node.js'

        - script: npm ci
          displayName: 'Install Dependencies'

        - script: npm run test -- --watch=false --no-progress --browsers=ChromeHeadless --code-coverage
          displayName: 'Run Angular Unit Tests'

- stage: DockerBuildAndPush
  displayName: Build & Push Angular UI Docker Image
  #condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
    - job: DockerJob
      steps:
        - task: Docker@2
          displayName: 'Login to Docker Hub'
          inputs:
            command: login
            containerRegistry: 'DockerHub'

        - task: Docker@2
          displayName: 'Build Angular UI Docker Image'
          inputs:
            command: build
            Dockerfile: $(dockerfilePath)
            repository: $(dockerHubRepo)
            tags: |
              ui_latest
              ui_$(shortSha)

        - task: Docker@2
          displayName: 'Push Angular UI Docker Image'
          inputs:
            command: push
            repository: $(dockerHubRepo)
            tags: |
              ui_latest
              ui_$(shortSha)