trigger: none

pool:
  name: "Comp367_SH_Agent"

variables:
  dockerHubRepo: 'ronaldjrombao/comp367group'
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 8)]
  containerName: 'budget-ui'
  networkName: 'comp367-net'
  exposedPort: '80'

stages:
- stage: DeployUI
  displayName: Deploy Angular UI via Docker
  jobs:
    - job: DeployJob
      steps:
        - task: Docker@2
          displayName: 'Login to Docker Hub'
          inputs:
            command: login
            containerRegistry: 'DockerHub'

        - script: |
            echo "Creating Docker network if it does not exist..."
            docker network inspect $(networkName) >nul 2>&1
            if errorlevel 1 (
              echo "Network does not exist. Creating..."
              docker network create $(networkName)
            ) else (
              echo "Network $(networkName) already exists."
            )
          displayName: 'Ensure Docker Network Exists'

        - script: |
            echo "Stopping and removing existing UI container if any..."
            docker rm -f $(containerName) >nul 2>&1 || echo "No container to remove."

            echo "Pulling latest UI image..."
            docker pull $(dockerHubRepo):ui_latest

            echo "Running UI container..."
            docker run -d --name $(containerName) --network $(networkName) -p $(exposedPort):80 $(dockerHubRepo):ui_latest
          displayName: 'Deploy UI Container'
