trigger: none

pool:
  name: "Comp367_SH_Agent"

variables:
  dockerHubRepo: 'ronaldjrombao/comp367group'
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 8)]
  containerName: 'budget-ui'
  networkName: 'comp367-net'
  exposedPort: '80'

stages:
- stage: DeployUI
  displayName: Deploy Angular UI via Docker
  jobs:
    - job: DeployJob
      steps:
        - task: Docker@2
          displayName: 'Login to Docker Hub'
          inputs:
            command: login
            containerRegistry: 'DockerHub'

        - script: |
            echo "Creating Docker network if not exists..."
            docker network inspect $(networkName) >/dev/null 2>&1 || docker network create $(networkName)
          displayName: 'Ensure Docker Network Exists'

        - script: |
            echo "Stopping and removing existing UI container if any..."
            docker rm -f $(containerName) || echo "No container to remove."

            echo "Pulling latest UI image..."
            docker pull $(dockerHubRepo):ui_latest

            echo "Running UI container..."
            docker run -d --name $(containerName) `
              --network $(networkName) `
              -p $(exposedPort):80 `
              $(dockerHubRepo):ui_latest
          displayName: 'Deploy UI Container'
